name: project_rpll
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: ^6.1.5+1
  camera: ^0.10.5+9
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  http: ^1.6.0
  tflite_flutter: ^0.12.1
  image: ^4.5.4
  geolocator: ^14.0.2
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/model_pisang.tflite
    - assets/model/labels_pisang.txt
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/icons.png"
  min_sdk_android: 21
